### ISSUE TITLE
Suggestions / Requests

### ISSUE THREAD

**Issue by Nephalem0** [chasem-dev/CobblemonExtras#11]
hi!
I really love the mod but I was hoping to ask if it would be possible to add a few features

- adding IV% and EV% on Pokeshout
- allowing to Pokeshout your entire party rather than individually
- while comptake is nice. I'd love for a /pc other command to just fully open another players pc

**Comment by chasem-dev** [comment]
Hi, sorry for the late reply to your issue.

IVs and EV % were added to pokeshout, /pokeshoutall is now a thing, and `/compseeother` can be used to view a players PC.
