### ISSUE TITLE
Fabric client won't start in IntelliJ

### ISSUE THREAD

**Issue by JimiIT92** [chasem-dev/CobblemonExtras#9]
Hi, I'm trying to run the mod from IntelliJ to see if I can contribute, but when I run the Fabric client the game fails to load (it actually loops stuck in the loading screen) spamming this error message. All I did was just clone the repository and import the project in Intellij (if I build the project I get a build successful. Also the Forge client run without issues)

[https://pastebin.com/Zv27mbWu](https://pastebin.com/Zv27mbWu)

**Comment by chasem-dev** [comment]
Both Forge and Fabric will now run from your local IDE!
